language: php
php:
  - '5.5'

before_script:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws s3 cp s3://keinewaste/travis.parameters config/properties/
  - ant -Denv=travis

addons:
  hosts:
    - api.local.keinewaste.org

script: vendor/bin/codecept run unit

notifications:
  slack: hackerstolz-community:Z5iWPCZHRCQPu1Cqmjh1KtLX
