language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'

before_script:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws s3 cp s3://keinewaste/travis.parameters config/properties/
  - ant -Denv=travis

script: vendor/bin/codecept run